### ISSUE TITLE
fatal: could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by artslob** [taiki-e/checkout-action#7] opened 2024-12-30 02:54 UTC
I get following error when I run this action in job inside docker on self-hosted runner (github repo is private):
```
Run taiki-e/checkout-action@v1.3.1
Run set -eu
git version
  git version 2.43.0
git config --global --add safe.directory /__w/test-github-runner/test-github-runner
git init
git remote add origin https://github.com/artslob/test-github-runner
git config --local gc.auto 0
git fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +305159c8fca5513d64cae6962980080b181968ba:refs/remotes/origin/tmp
  fatal: could not read Username for 'https://github.com/': No such device or address
  fatal: could not read Username for 'https://github.com/': No such device or address
  fatal: could not read Username for 'https://github.com/': No such device or address
  fatal: could not read Username for 'https://github.com/': No such device or address
  fatal: could not read Username for 'https://github.com/': No such device or address
  fatal: could not read Username for 'https://github.com/': No such device or address
  fatal: could not read Username for 'https://github.com/': No such device or address
  fatal: could not read Username for 'https://github.com/': No such device or address
  fatal: could not read Username for 'https://github.com/': No such device or address
  fatal: could not read Username for 'https://github.com/': No such device or address
  fatal: could not read Username for 'https://github.com/': No such device or address
  Error: Process completed with exit code 128.
```

Set up job log looks like this:
```
Current runner version: '2.321.0'
Runner name: 'test-github-runner'
Runner group name: 'Default'
Machine name: 'alfa'
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
  Packages: read
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'taiki-e/checkout-action@v1.3.1' (SHA:b13d20b7cda4e2f325ef19895128f7ff735c0b3d)
Download action repository 'dtolnay/rust-toolchain@stable' (SHA:1ff72ee08e3cb84d84adba594e0a297990fc1ed3)
Complete job name: Check
```

Action looks like this:
```
jobs:
  check:
    name: Check
    runs-on: self-hosted
    container: ubuntu:latest
    steps:
      - name: Install deps
        run: apt-get update && apt-get install -y curl unzip build-essential git
      - uses: taiki-e/checkout-action@v1.3.1
```

**Comment by taiki-e** [comment] 2024-12-30 02:57
Duplicate of https://github.com/taiki-e/checkout-action/issues/1.

**Closed by taiki-e** 2024-12-30 02:57 UTC
